name: Build and Test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Run Tests
      run: dotnet test --no-build --verbosity normal

    - name: Check code formatting
      run: dotnet format --verify-no-changes
      
    - name: Read secret
      run: echo "Secret value is ${{ secrets.MY_SECRET }}"

    - name: Simulated deploy
      run: bash ./deploy.sh
      
    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build Docker image
      run: docker build -t ghcr.io/8alex62/modernsoftwareapp:latest .

    - name: Push Docker image
      run: docker push ghcr.io/8alex62/modernsoftwareapp:latest
